<%@ page contentType="text/html;charset=UTF-8" language="java" %>
<%@ include file="../shared/navbar.jspf" %>
<!DOCTYPE html>
<html>
  <head>
    <title>Ledger Reports - Crown Capital Bank</title>
    <link rel="stylesheet" href="../static/css/style.css">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
  </head>
  <body>
<div class="container">
    <div class="hero">
        <h1>📊 Ledger Reports</h1>
        <p>View and download end-of-day ledger reports</p>
    </div>
    <div class="card">
        <h3>Ledger Reports</h3>
        <table class="table">
            <thead>
                <tr>
                    <th>Date</th>
                    <th>Report Type</th>
                    <th>Generated By</th>
                    <th>File</th>
                    <th>Actions</th>
                </tr>
            </thead>
            <tbody>
                <tr>
                    <td>2024-01-20</td>
                    <td>DAILY_TRANSACTIONS</td>
                    <td>manager1</td>
                    <td>ledger_20240120.pdf</td>
                    <td><a href="#" class="btn btn-primary">Download</a></td>
                </tr>
                <tr>
                    <td>2024-01-19</td>
                    <td>LEDGER</td>
                    <td>manager1</td>
                    <td>ledger_20240119.pdf</td>
                    <td><a href="#" class="btn btn-primary">Download</a></td>
                </tr>
            </tbody>
        </table>
    </div>
</div>
<%@ include file="../shared/footer.jspf" %>
  </body>
</html>
